unit TestUControllerProduto;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Horse, UControllerProduto, System.JSON, System.SysUtils;

type
  // Test methods for class TControllerProduto

  TestTControllerProduto = class(TTestCase)
  strict private
    FControllerProduto: TControllerProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestInsertProduto;
    procedure TestGetProduto;
    procedure TestGetProdutoByID;
    procedure TestDeleteProdutoByID;
    procedure TestUpdateProduto;
    procedure TestRegistryRoutes;
  end;

implementation
//uses

procedure TestTControllerProduto.SetUp;
begin
  FControllerProduto := TControllerProduto.Create;
end;

procedure TestTControllerProduto.TearDown;
begin
  FControllerProduto.Free;
  FControllerProduto := nil;
end;

procedure TestTControllerProduto.TestInsertProduto;
var
  next: System.SysUtils.TProc;
  res: THorseResponse;
  req: THorseRequest;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.InsertProduto(req, res, next);
  // TODO: Validate method results
end;

procedure TestTControllerProduto.TestGetProduto;
var
  next: System.SysUtils.TProc;
  res: THorseResponse;
  req: THorseRequest;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.GetProduto(req, res, next);
  // TODO: Validate method results
end;

procedure TestTControllerProduto.TestGetProdutoByID;
var
  next: System.SysUtils.TProc;
  res: THorseResponse;
  req: THorseRequest;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.GetProdutoByID(req, res, next);
  // TODO: Validate method results
end;

procedure TestTControllerProduto.TestDeleteProdutoByID;
var
  next: System.SysUtils.TProc;
  res: THorseResponse;
  req: THorseRequest;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.DeleteProdutoByID(req, res, next);
  // TODO: Validate method results
end;

procedure TestTControllerProduto.TestUpdateProduto;
var
  next: System.SysUtils.TProc;
  res: THorseResponse;
  req: THorseRequest;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.UpdateProduto(req, res, next);
  // TODO: Validate method results
end;

procedure TestTControllerProduto.TestRegistryRoutes;
var
  App: THorse;
begin
  // TODO: Setup method call parameters
  //FControllerProduto.RegistryRoutes(App);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTControllerProduto.Suite);
end.

